### ISSUE TITLE
Release current master to official plugin repository as a version update

### ISSUE THREAD

**Issue by sbconslt** [cyberscribe/better-random-redirect#3]
Can you publish the latest changes from 11 months ago out to the official plugin please. I started performing work on the codebase of the plugin as served from the wordpress.org repo and was making progress cleaning things up only to find when I went to commit that the github version is ahead of the officially published plugin's codebase. Please sync things up so I can continue without having to work around the gap. Thanks.

**Comment by sbconslt** [comment]
Forget it, I wrote my own

**Comment by cyberscribe** [comment]
Have sync'd up now. If what you wrote might help others, please consider contributing @sbconslt

**Comment by sbconslt** [comment]
See if you want the changes in https://github.com/sbconslt/better-random-redirect/commit/af2e20f8f791494ece5d801d8d8d50d77a09d2f0 .... Oh it looks like you already pulled them. Ok thanks.

**Comment by cyberscribe** [comment]
Looks good; merged; thanks!
