### ISSUE TITLE
Warning: Undefined variable $tmp_additional_where

### ISSUE THREAD

**Issue by Hjorthmedh** [cyberscribe/better-random-redirect#5]
Been using your plugin for years. Unfortunately now I am getting an error from the better-random-direct plugin on wordpress:

Warning: Undefined variable $tmp_additional_where in wp-content/plugins/better-random-redirect/classes/QtranslatexFilter.php on line 41 Warning: Undefined variable $lang in wp-content/plugins/better-random-redirect/classes/BetterRandomRedirect.php on line 249 Warning: Cannot modify header information - headers already sent by (output started at wp-content/plugins/better-random-redirect/classes/QtranslatexFilter.php:41) in wp-includes/pluggable.php on line 1340 Warning: Cannot modify header information - headers already sent by (output started atwp-content/plugins/better-random-redirect/classes/QtranslatexFilter.php:41) in wp-includes/pluggable.php on line 1343

**Comment by cyberscribe** [comment]
Thanks. Not seeing this elsewhere so curious: are you using the Qtranslatex plugin? If so, did it recently get updated?

**Comment by cyberscribe** [comment]
Also, did you recently change your error reporting level in PHP? (This could be caused by changing hosts as well.)

**Comment by Hjorthmedh** [comment]
Don't use the Qtranslatex plugin, and have not done any changes in error report level. My language is set to en_GB if that might affect something?

Wordpress 5.8.2
Site language en_GB
PHP version 8.0.13 (Supports 64bit values)
Database 10.3.30-MariaDB-1:10.3.30+maria~focal

**Comment by Hjorthmedh** [comment]
I am using your plugin with the "Page Links To" plugin, not sure if that might cause a conflict? 

But that plugin was updated last 11 months ago, and this has worked since then. It says your plugin was updated four months ago, and I think it has worked since then, so something else must have changed.

**Comment by cyberscribe** [comment]
Because I can't reproduce it myself I'm flying blind a little bit, but please see if 1.3.16 has resolved this for you

**Comment by Hjorthmedh** [comment]
That worked. Great! Curious, what do you think was the issue?

**Comment by cyberscribe** [comment]
It seems like something where a PHP upgrade or change in error reporting started spitting these out, causing the chain reaction with your "headers already sent" message. In any case, good to resolve in case others come across it.
