### ISSUE TITLE
Multiple Categories

### ISSUE THREAD

**Issue by DeepanshKhurana** [cyberscribe/better-random-redirect#6]
Hi, Robert! Thank you for the wonderful plugin. I was hoping if you have any plans or quick fix (which I can use locally) to enable the dropdown selector for categories to be able to select multiple categories?

I would submit a PR but my limited skills in PHP would be a great limiter.

If this is something you cannot help with, please feel free to close this issue.

Thank you.

----

To add, in case it helps in some way, I was able to achieve the functionality using the [Redirect URL to Post](https://chattymango.com/redirect-url-to-post/) plugin, and setting the url to `/?redirect_to=random&each_once=rewind&lock=1&cat=<all cat ids>` then alias it to `/random-post` to get it to work.

But of course, this needs me to use two plugins, which is not a problem for me as such.

I will leave this here in case this helps you make the change if you have the time.

Cheers!

----

**Comment by cyberscribe** [comment]
Unfortunately it's not a simple matter to support multiple categories. However, what most people do is create a new category (like "random") and use that category for all posts they want to include in the random redirect.

**Comment by DeepanshKhurana** [comment]
> Unfortunately it's not a simple matter to support multiple categories. However, what most people do is create a new category (like "random") and use that category for all posts they want to include in the random redirect.

Thank you for your response. I can understand it may not be as straightforward. Also, the "random" idea may work if I can manage to hack away some conditional to remove it from the UI. In any case, I appreciate the package and the reply. Have a great weekend!

**Comment by cyberscribe** [comment]
Good luck! This may help: https://www.wpbeginner.com/wp-tutorials/how-to-display-a-category-only-if-it-has-posts-in-wordpress/
